version: '3.7'

services:
  frontend:
    restart: unless-stopped
    image: fabianomarino/frontend-app:1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:80
  backend:
    restart: unless-stopped
    image: fabianomarino/backend-app:1.0
    container_name: backend
    ports:
      - 8080:8080
    environment:
     - spring.datasource.url=jdbc:postgresql://db:5432/postgres
     - spring.datasource.username=postgres
     - spring.datasource.password=postgres
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
