name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Die Pipeline wird bei jedem Push in den Main-Branch ausgelöst

jobs:
  remote-command:
    runs-on: ubuntu-latest
    
    steps:
      # Checke das Repository aus
      - name: Checkout repository
        uses: actions/checkout@v2

      # Kopiere die run.sh-Datei auf den Remote-Server und führe sie aus
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JUMP_HOST }}
          username: ${{ secrets.JUMP_USERNAME }}
          password: ${{ secrets.JUMP_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          script: |
            # Kopiere das run.sh Skript auf den Remote-Server
            scp run.sh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }}:/home/${{ secrets.JUMP_USERNAME }}/run.sh
            
            # Auf dem Remote-Server das Skript ausführbar machen und ausführen
            ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} 'chmod +x /home/${{ secrets.JUMP_USERNAME }}/run.sh && /home/${{ secrets.JUMP_USERNAME }}/run.sh'
