name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Die Pipeline wird bei jedem Push in den Main-Branch ausgelöst

jobs:
  remote-command:
    runs-on: ubuntu-latest
    
    steps:
      # Checke das Repository aus
      - name: Checkout repository
        uses: actions/checkout@v2

      # Verbinde dich mit dem Remote-Server und führe einen Befehl aus
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: echo "Hello World"

      - name: Upload run.sh to remote server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./run.sh"
          target: "~/run.sh"

      - name: Execute run.sh on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
           chmod +x ~/run.sh
            ./run.sh


          
