name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Die Pipeline wird bei jedem Push in den Main-Branch ausgelöst

jobs:
  remote-command:
    runs-on: ubuntu-latest
    
    steps:
      # Checke das Repository aus
      - name: Checkout repository
        uses: actions/checkout@v2

      # Verbinde dich mit dem Remote-Server und führe einen Befehl aus
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JUMP_HOST }}
          username: ${{ secrets.JUMP_USERNAME }}
          password: ${{ secrets.JUMP_PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD}}
          script: echo "Hello World"
