name: Hello World Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello World"

    - name: Print Secret
      run: echo $MY_SECRET

    - name: Give execution permission for run.sh
      run: chmod +x ./run.sh  

    - name: Run Hello World Script
      run: ./run.sh  
