name: Execute Remote SSH Commands

on:
  push:
    branches:
      - main

jobs:
  remote-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
         echo "Copying run.sh to server"
         scp run.sh ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/path/to/destination
         bash /path/to/destination/run.sh
